# Generated by Django 6.0 on 2026-01-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='user',
        ),
        migrations.AddField(
            model_name='checkin',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('due', 'Due'), ('safe', 'Safe'), ('unsafe', 'Unsafe'), ('missed', 'Missed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='message',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkin',
            name='mood',
            field=models.CharField(blank=True, default='', max_length=20),
            preserve_default=False,
        ),
    ]
