# Generated by Django 6.0.1 on 2026-03-28 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhraseDetectionEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255)),
                ('text', models.TextField()),
                ('processed_text', models.TextField(blank=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('method', models.CharField(choices=[('ml', 'ML Classification'), ('keyword_boost', 'Keyword Boost'), ('keyword_only', 'Keyword Only Fallback')], default='ml', max_length=20)),
                ('matched_keyword', models.CharField(blank=True, max_length=100, null=True)),
                ('sos_triggered', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
